// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp.Interactions {
public class Interaction {
	public long OccurredAt { get; set; }
	public InteractiveElement InteractiveElement { get; set; }
	public Actor Actor { get; set; }
	public Transform ActorTransform { get; set; }

	public Interaction() {
	}
}
}

